DECLARE @TableName varchar(100)
SET @TableName = 'Taverns'

SELECT 
CONCAT('CREATE TABLE ',TABLE_NAME, ' (') as queryPiece 
FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_NAME = @TableName
UNION ALL
SELECT CONCAT(cols.COLUMN_NAME, ' ', cols.DATA_TYPE, 
(CASE WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL 
Then CONCAT('(', CAST(CHARACTER_MAXIMUM_LENGTH as varchar(100)), 
')') Else '' END), 
','
-- CASE WHEN ORDINAL_POSITION != (SELECT MAX(ORDINAL_POSITION) FROM INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = @TableName) THEN ',' ELSE '' END
) as queryPiece FROM 
INFORMATION_SCHEMA.COLUMNS as cols WHERE
TABLE_NAME = @TableName
UNION ALL
SELECT 
CONCAT('PRIMARY KEY (', k.COLUMN_NAME, '),')
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS as t JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k ON t.CONSTRAINT_NAME = k.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as r ON t.CONSTRAINT_NAME = r.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as a ON a.CONSTRAINT_NAME = r.UNIQUE_CONSTRAINT_NAME
WHERE t.TABLE_NAME = @TableName and t.CONSTRAINT_TYPE = 'PRIMARY KEY'
UNION ALL
SELECT 
CONCAT('FOREIGN KEY (', k.COLUMN_NAME,') REFERENCES ',a.TABLE_NAME,'(', a.COLUMN_NAME, '),')
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS as t JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k ON t.CONSTRAINT_NAME = k.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as r ON t.CONSTRAINT_NAME = r.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as a ON a.CONSTRAINT_NAME = r.UNIQUE_CONSTRAINT_NAME
WHERE t.TABLE_NAME = @TableName and t.CONSTRAINT_TYPE = 'FOREIGN KEY'
UNION ALL
SELECT ')';


/*

select * from INFORMATION_SCHEMA.TABLE_CONSTRAINTS --41 RowsssELECT * from INFORMATION_SCHEMA.KEY_COLUMN_USAGE --42 Rowsselect * from INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS --21 Rows



SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS as t JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k ON t.CONSTRAINT_NAME = k.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as r ON t.CONSTRAINT_NAME = r.CONSTRAINT_NAME


SELECT t.CONSTRAINT_NAME, t.TABLE_NAME, k.COLUMN_NAME, t.CONSTRAINT_TYPE, r.UNIQUE_CONSTRAINT_NAME, a.TABLE_NAME, a.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS as t JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k ON t.CONSTRAINT_NAME = k.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as r ON t.CONSTRAINT_NAME = r.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as a ON a.CONSTRAINT_NAME = r.UNIQUE_CONSTRAINT_NAME
where t.TABLE_NAME = 'Taverns' and t.CONSTRAINT_TYPE = 'PRIMARY KEY'


SELECT g.*,g.Name, c.Name, l.Level FROM Levels as l RIGHT JOIN Guests as g ON l.GuestID = g.ID LEFT JOIN Classes c ON l.ClassID = c.ID
SELECT g.Name, c.Name, l.Level FROM Levels as l RIGHT JOIN Guests as g ON l.GuestID = g.ID LEFT JOIN Classes c ON l.ClassID = c.ID

SELECT * FROM Guests
SELECT * FROM Classes
SELECT * FROM Levels


*/